"""Removing Birthdate and Fullname

Revision ID: e476c0ee1703
Revises: c4c43f179409
Create Date: 2024-11-11 14:27:38.852254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e476c0ee1703'
down_revision: Union[str, None] = 'c4c43f179409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
